name: shopping_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  carousel_slider: 4.1.1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  introduction_screen: ^3.0.2
  lottie: ^1.4.0
  get_storage: 2.0.3
  firebase_core: 1.20.0
  firebase_auth: 3.6.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/gambar/
    - assets/lotties/
  uses-material-design: true

